apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight
  labels:
    app  : lab4
    owner: MrsOwlya
spec:
  selector:
    matchLabels:
      project: lab4
  template:
    metadata:
      labels:
        project: lab4
    spec:
      containers:
        - name : flight
          image: mrsowlya/flight:latest
          ports:
            - containerPort: 8060

---
apiVersion: v1
kind: Service
metadata:
  name: flight
  labels:
    app  : lab4
    owner: MrsOwlya
spec:
  selector:
    project: lab4
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 8060
      targetPort: 8060
  type: ClusterIP