apiVersion: v1
kind: Pod
metadata:
  name: gateway
  labels:
    env  : prod
    app  : main
    owner: MrsOwlya
spec:
  containers:
    - name : gateway
      image: mrsowlya/gateway:latest
      ports:
        - containerPort: 8080