apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight
  labels:
    app  : lab4
    owner: MrsOwlya
spec:
  selector:
    matchLabels:
      project: lab4
  template:
    metadata:
      labels:
        project: lab4
    spec:
      containers:
        - name : gateway
          image: mrsowlya/gateway:latest
          ports:
            - containerPort: 8080

        - name : ticket
          image: mrsowlya/ticket:latest
          ports:
            - containerPort: 8070

        - name : flight
          image: mrsowlya/flight:latest
          ports:
            - containerPort: 8060

        - name : bonus
          image: mrsowlya/bonus:latest
          ports:
            - containerPort: 8050

---
apiVersion: v1
kind: Service
metadata:
  name: flight
  labels:
    app  : lab4
    owner: MrsOwlya
spec:
  type: LoadBalancer
  selector:
    project: lab4
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80
      targetPort: 8080